# Generated by Django 3.0.7 on 2020-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('Zip', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(default='United States', max_length=200, null=True)),
                ('EIN', models.CharField(max_length=200, null=True)),
                ('no_of_consultants', models.IntegerField(blank=True, editable=False, null=True)),
                ('preferred_vendor', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=40)),
                ('agreement_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('inprogress', 'In Progress'), ('under process', 'Under Review')], max_length=200)),
            ],
        ),
    ]
