# Generated by Django 3.0.7 on 2020-08-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='Zip',
            new_name='zipp',
        ),
    ]
