# Generated by Django 3.0.7 on 2020-08-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200804_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='EIN',
            new_name='ein',
        ),
    ]
