# Generated by Django 3.0.7 on 2020-08-04 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20200804_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
