# Generated by Django 3.0.7 on 2020-08-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendors_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='fax',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
