# Generated by Django 3.0.7 on 2020-08-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20200805_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='agreement_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='preferred_vendor',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
