# Generated by Django 3.0.7 on 2020-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_auto_20200805_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='desk_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
