# Generated by Django 3.0.7 on 2020-08-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20200806_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='vendor',
        ),
    ]
