# Generated by Django 3.0.7 on 2020-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_remove_contacts_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='country',
            field=models.CharField(default='United States', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='mobile',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='zipp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
